In [62]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Part 1: Reading & Exploring Data

In [63]:
df=pd.read_excel("F:/Instant (AI & Data Science)/student_performance_data - student_performance_data.xlsx")
# Display the first 5 rows of the dataset
df.head()

,StudentID,Gender,Age,StudyHoursPerWeek,AttendanceRate,GPA,Major,PartTimeJob,ExtraCurricularActivities
0,1,Male,24,37,90.75,3.47,Arts,Yes,No
1,2,Female,22,37,74.90,2.32,Education,No,No
2,3,Male,22,10,53.36,2.38,Business,No,No
3,4,Male,24,10,70.26,3.46,Science,Yes,No
4,5,Male,18,19,74.87,2.31,Education,Yes,No

In [64]:
# Display the last 7 rows of the dataset
df.tail(7)

,StudentID,Gender,Age,StudyHoursPerWeek,AttendanceRate,GPA,Major,PartTimeJob,ExtraCurricularActivities
493,494,Female,22,34,76.09,3.41,Engineering,No,No
494,495,Male,24,23,67.13,2.11,Business,No,Yes
495,496,Male,22,37,76.61,2.97,Science,No,No
496,497,Male,23,11,56.29,3.20,Science,No,No
497,498,Female,20,6,56.64,3.20,Science,No,Yes
498,499,Male,22,18,57.18,2.05,Business,No,Yes
499,500,Female,24,21,96.99,2.64,Engineering,No,No

In [65]:
# Data types of each column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   StudentID                  500 non-null    int64
 1   Gender                     500 non-null    object
 2   Age                        500 non-null    int64
 3   StudyHoursPerWeek          500 non-null    int64
 4   AttendanceRate             500 non-null    float64
 5   GPA                        500 non-null    float64
 6   Major                      500 non-null    object
 7   PartTimeJob                500 non-null    object
 8   ExtraCurricularActivities  500 non-null    object
dtypes: float64(2), int64(3), object(4)
memory usage: 35.3+ KB

In [66]:
# Number of non-null values 
df.isnull().sum()

StudentID                    0
Gender                       0
Age                          0
StudyHoursPerWeek            0
AttendanceRate               0
GPA                          0
Major                        0
PartTimeJob                  0
ExtraCurricularActivities    0
dtype: int64

In [67]:
# Dataset dimensions (rows and columns)
df.shape

(500, 9)

In [68]:
# Summary statistics for numerical columns 
df.describe()

        StudentID         Age  StudyHoursPerWeek  AttendanceRate        GPA
count  500.000000  500.000000         500.000000      500.000000  500.00000
mean   250.500000   20.956000          19.876000       74.990380    2.98516
std    144.481833    2.000517          11.471347       14.565917    0.56362
min      1.000000   18.000000           1.000000       50.010000    2.00000
25%    125.750000   19.000000          10.000000       62.607500    2.48750
50%    250.500000   21.000000          20.500000       75.730000    3.00000
75%    375.250000   23.000000          30.000000       87.220000    3.48000
max    500.000000   24.000000          39.000000       99.970000    3.99000

Selecting & Filtering

In [69]:
# Display the following columns only: 
# • StudentID 
# • Gender 
# • GPA
df.iloc[: , 0:3]

     StudentID  Gender  Age
0            1    Male   24
1            2  Female   22
2            3    Male   22
3            4    Male   24
4            5    Male   18
..         ...     ...  ...
495        496    Male   22
496        497    Male   23
497        498  Female   20
498        499    Male   22
499        500  Female   24

[500 rows x 3 columns]

In [70]:
# Using loc, display rows 5 to 12.
df.loc[5:12]

,StudentID,Gender,Age,StudyHoursPerWeek,AttendanceRate,GPA,Major,PartTimeJob,ExtraCurricularActivities
5,6,Female,20,17,86.01,2.47,Business,Yes,No
6,7,Male,19,21,55.33,3.93,Arts,No,No
7,8,Male,18,14,57.00,2.51,Education,No,No
8,9,Male,19,9,63.18,3.32,Business,No,No
9,10,Female,24,1,63.32,3.96,Engineering,Yes,Yes
10,11,Male,23,13,86.61,2.75,Engineering,Yes,No
11,12,Male,19,4,62.54,2.04,Science,No,Yes
12,13,Male,20,1,81.65,2.49,Business,No,No

In [71]:
# Using iloc, display the first 8 rows and the first 4 columns
df.iloc[0:8, 0:4]

   StudentID  Gender  Age  StudyHoursPerWeek
0          1    Male   24                 37
1          2  Female   22                 37
2          3    Male   22                 10
3          4    Male   24                 10
4          5    Male   18                 19
5          6  Female   20                 17
6          7    Male   19                 21
7          8    Male   18                 14

In [72]:
# Display all students whose Age is greater than 20.
df[df["Age"]>20]

,StudentID,Gender,Age,StudyHoursPerWeek,AttendanceRate,GPA,Major,PartTimeJob,ExtraCurricularActivities
0,1,Male,24,37,90.75,3.47,Arts,Yes,No
1,2,Female,22,37,74.90,2.32,Education,No,No
2,3,Male,22,10,53.36,2.38,Business,No,No
3,4,Male,24,10,70.26,3.46,Science,Yes,No
9,10,Female,24,1,63.32,3.96,Engineering,Yes,Yes
...,...,...,...,...,...,...,...,...,...
494,495,Male,24,23,67.13,2.11,Business,No,Yes
495,496,Male,22,37,76.61,2.97,Science,No,No
496,497,Male,23,11,56.29,3.20,Science,No,No
498,499,Male,22,18,57.18,2.05,Business,No,Yes
499,500,Female,24,21,96.99,2.64,Engineering,No,No

In [73]:
# Display all students who satisfy both conditions: 
# • GPA greater than 3.5 
# • Attendance greater than 80
df[(df["GPA"] > 3.5) & (df["AttendanceRate"] > 80)]

,StudentID,Gender,Age,StudyHoursPerWeek,AttendanceRate,GPA,Major,PartTimeJob,ExtraCurricularActivities
15,16,Male,24,28,91.91,3.54,Business,Yes,No
17,18,Female,24,8,88.55,3.59,Arts,No,Yes
20,21,Female,20,34,97.93,3.88,Education,Yes,No
28,29,Female,23,23,86.08,3.73,Engineering,No,No
29,30,Female,24,15,80.52,3.99,Science,Yes,Yes
38,39,Male,21,38,92.08,3.80,Arts,Yes,No
39,40,Male,19,34,92.32,3.76,Engineering,Yes,Yes
58,59,Male,20,20,98.10,3.52,Education,No,Yes
63,64,Male,22,2,97.91,3.83,Arts,Yes,Yes
64,65,Male,23,13,87.92,3.63,Engineering,Yes,Yes
77,78,Female,18,3,99.97,3.79,Science,Yes,No
96,97,Female,19,27,94.25,3.65,Business,No,Yes
103,104,Female,19,36,83.08,3.59,Education,No,Yes
154,155,Male,19,33,91.53,3.64,Education,No,Yes
187,188,Male,20,5,86.76,3.51,Arts,No,Yes
191,192,Male,22,19,84.79,3.64,Education,Yes,No
194,195,Male,22,20,98.11,3.96,Business,Yes,Yes
201,202,Female,21,11,95.33,3.54,Education,No,No
206,207,Female,23,6,86.70,3.58,Business,Yes,Yes
219,220,Male,23,9,98.07,3.65,Business,No,No
221,222,Male,20,15,93.95,3.88,Education,Yes,Yes
237,238,Female,19,29,90.93,3.64,Arts,Yes,Yes
242,243,Female,20,30,92.01,3.91,Business,Yes,No
251,252,Male,18,25,88.55,3.66,Education,No,Yes
264,265,Male,23,17,91.08,3.87,Education,Yes,Yes
277,278,Female,21,30,92.00,3.51,Science,Yes,Yes
296,297,Female,24,31,85.75,3.58,Business,Yes,Yes
329,330,Female,19,36,98.73,3.62,Arts,Yes,Yes
331,332,Male,22,5,82.85,3.72,Business,Yes,Yes
333,334,Male,23,8,97.63,3.91,Engineering,Yes,Yes
344,345,Male,21,21,88.79,3.65,Education,Yes,Yes
353,354,Female,24,10,98.87,3.98,Education,Yes,Yes
359,360,Male,23,38,97.58,3.60,Engineering,Yes,No
366,367,Female,19,17,96.76,3.94,Business,Yes,Yes
367,368,Female,21,24,97.37,3.88,Arts,Yes,No
368,369,Male,21,25,81.27,3.57,Business,No,Yes
372,373,Female,24,33,83.04,3.66,Education,No,No
380,381,Female,21,20,86.24,3.95,Education,No,No
388,389,Male,21,30,93.59,3.79,Education,No,Yes
407,408,Female,18,8,81.44,3.86,Arts,No,No
419,420,Female,21,32,82.75,3.96,Business,No,Yes
425,426,Male,19,24,91.80,3.51,Engineering,Yes,No
464,465,Female,22,23,80.28,3.68,Engineering,No,No
468,469,Male,18,37,85.27,3.52,Engineering,No,No
470,471,Male,24,30,93.21,3.51,Arts,Yes,No

In [74]:
# Display all students whose Major is Engineering and have a PartTimeJob. 
df[(df["Major"]=="Engineering")& (df["PartTimeJob"]=="Yes")]

,StudentID,Gender,Age,StudyHoursPerWeek,AttendanceRate,GPA,Major,PartTimeJob,ExtraCurricularActivities
9,10,Female,24,1,63.32,3.96,Engineering,Yes,Yes
10,11,Male,23,13,86.61,2.75,Engineering,Yes,No
13,14,Male,23,32,74.71,3.66,Engineering,Yes,No
18,19,Female,19,39,71.10,3.84,Engineering,Yes,Yes
31,32,Male,19,21,69.83,2.18,Engineering,Yes,Yes
39,40,Male,19,34,92.32,3.76,Engineering,Yes,Yes
41,42,Male,18,30,57.73,3.74,Engineering,Yes,No
55,56,Female,24,17,55.15,3.17,Engineering,Yes,No
64,65,Male,23,13,87.92,3.63,Engineering,Yes,Yes
65,66,Female,19,11,81.95,2.22,Engineering,Yes,No
71,72,Female,23,8,82.33,3.10,Engineering,Yes,Yes
73,74,Female,23,4,52.58,3.43,Engineering,Yes,Yes
94,95,Female,19,14,78.03,2.80,Engineering,Yes,Yes
119,120,Male,24,3,51.88,2.72,Engineering,Yes,No
122,123,Female,23,38,63.58,3.11,Engineering,Yes,No
130,131,Female,22,17,64.85,2.30,Engineering,Yes,No
131,132,Male,23,39,92.64,2.85,Engineering,Yes,Yes
149,150,Female,23,6,87.17,2.89,Engineering,Yes,No
172,173,Male,19,6,73.17,3.19,Engineering,Yes,No
178,179,Male,21,15,72.87,2.76,Engineering,Yes,No
181,182,Male,18,38,73.83,2.89,Engineering,Yes,Yes
186,187,Female,19,26,96.58,3.27,Engineering,Yes,No
215,216,Male,22,1,55.29,2.76,Engineering,Yes,Yes
217,218,Male,19,9,59.46,2.48,Engineering,Yes,No
224,225,Female,21,35,61.43,3.57,Engineering,Yes,No
227,228,Female,19,5,77.81,2.78,Engineering,Yes,Yes
239,240,Female,18,11,64.17,2.05,Engineering,Yes,Yes
241,242,Male,18,14,71.61,2.45,Engineering,Yes,Yes
258,259,Female,23,38,83.80,3.01,Engineering,Yes,Yes
263,264,Male,18,25,53.28,3.19,Engineering,Yes,No
283,284,Male,24,33,51.57,3.57,Engineering,Yes,Yes
304,305,Female,19,4,72.68,3.93,Engineering,Yes,Yes
313,314,Male,21,5,50.06,2.65,Engineering,Yes,Yes
314,315,Male,18,20,79.92,3.67,Engineering,Yes,No
333,334,Male,23,8,97.63,3.91,Engineering,Yes,Yes
335,336,Female,22,31,86.21,2.20,Engineering,Yes,Yes
341,342,Female,24,23,74.12,3.86,Engineering,Yes,Yes
345,346,Male,21,26,97.06,2.99,Engineering,Yes,No
348,349,Female,24,1,94.13,2.45,Engineering,Yes,Yes
355,356,Male,19,35,84.66,2.10,Engineering,Yes,No
357,358,Female,20,26,52.06,3.49,Engineering,Yes,Yes
359,360,Male,23,38,97.58,3.60,Engineering,Yes,No
373,374,Female,18,29,77.65,2.14,Engineering,Yes,No
390,391,Male,22,19,52.18,2.25,Engineering,Yes,Yes
392,393,Female,24,30,51.04,2.23,Engineering,Yes,No
395,396,Female,22,30,77.12,3.04,Engineering,Yes,No
401,402,Female,20,2,60.18,2.19,Engineering,Yes,Yes
409,410,Female,24,39,88.39,2.99,Engineering,Yes,Yes
425,426,Male,19,24,91.80,3.51,Engineering,Yes,No
427,428,Female,21,8,88.80,3.08,Engineering,Yes,No
439,440,Male,24,16,78.97,3.22,Engineering,Yes,No
456,457,Female,24,18,83.47,3.48,Engineering,Yes,No
459,460,Male,19,5,79.39,3.38,Engineering,Yes,Yes
462,463,Female,20,2,67.96,3.05,Engineering,Yes,Yes
463,464,Male,22,3,68.97,3.70,Engineering,Yes,Yes
475,476,Female,24,24,56.15,2.77,Engineering,Yes,No
484,485,Male,18,9,84.41,2.33,Engineering,Yes,Yes
490,491,Female,23,4,98.65,3.45,Engineering,Yes,Yes

Part 3: Modifying Data

In [75]:
# Create a new column called Performance using the following rule: 
# • If GPA >= 3.5 → "Excellent" 
# • Otherwise → "Good" 
df["Performance"] = df["GPA"].apply(lambda x: "Excellent" if x >= 3.5 else "Good")
df

,StudentID,Gender,Age,StudyHoursPerWeek,AttendanceRate,GPA,Major,PartTimeJob,ExtraCurricularActivities,Performance
0,1,Male,24,37,90.75,3.47,Arts,Yes,No,Good
1,2,Female,22,37,74.90,2.32,Education,No,No,Good
2,3,Male,22,10,53.36,2.38,Business,No,No,Good
3,4,Male,24,10,70.26,3.46,Science,Yes,No,Good
4,5,Male,18,19,74.87,2.31,Education,Yes,No,Good
...,...,...,...,...,...,...,...,...,...,...
495,496,Male,22,37,76.61,2.97,Science,No,No,Good
496,497,Male,23,11,56.29,3.20,Science,No,No,Good
497,498,Female,20,6,56.64,3.20,Science,No,Yes,Good
498,499,Male,22,18,57.18,2.05,Business,No,Yes,Good
499,500,Female,24,21,96.99,2.64,Engineering,No,No,Good

In [76]:
# Rename the column StudyHour to StudyHours.
df.rename(columns={"StudyHoursPerWeek": "StudyHours"})

,StudentID,Gender,Age,StudyHours,AttendanceRate,GPA,Major,PartTimeJob,ExtraCurricularActivities,Performance
0,1,Male,24,37,90.75,3.47,Arts,Yes,No,Good
1,2,Female,22,37,74.90,2.32,Education,No,No,Good
2,3,Male,22,10,53.36,2.38,Business,No,No,Good
3,4,Male,24,10,70.26,3.46,Science,Yes,No,Good
4,5,Male,18,19,74.87,2.31,Education,Yes,No,Good
...,...,...,...,...,...,...,...,...,...,...
495,496,Male,22,37,76.61,2.97,Science,No,No,Good
496,497,Male,23,11,56.29,3.20,Science,No,No,Good
497,498,Female,20,6,56.64,3.20,Science,No,Yes,Good
498,499,Male,22,18,57.18,2.05,Business,No,Yes,Good
499,500,Female,24,21,96.99,2.64,Engineering,No,No,Good

In [78]:
# Delete the column ExtraCurricularActivities.
df.drop("ExtraCurricularActivities", axis=1)

,StudentID,Gender,Age,StudyHoursPerWeek,AttendanceRate,GPA,Major,PartTimeJob,Performance
0,1,Male,24,37,90.75,3.47,Arts,Yes,Good
1,2,Female,22,37,74.90,2.32,Education,No,Good
2,3,Male,22,10,53.36,2.38,Business,No,Good
3,4,Male,24,10,70.26,3.46,Science,Yes,Good
4,5,Male,18,19,74.87,2.31,Education,Yes,Good
...,...,...,...,...,...,...,...,...,...
495,496,Male,22,37,76.61,2.97,Science,No,Good
496,497,Male,23,11,56.29,3.20,Science,No,Good
497,498,Female,20,6,56.64,3.20,Science,No,Good
498,499,Male,22,18,57.18,2.05,Business,No,Good
499,500,Female,24,21,96.99,2.64,Engineering,No,Good

In [89]:
# Delete the row with index 10.
df.drop(df.index[10], axis=0).head(15)

,StudentID,Gender,Age,StudyHoursPerWeek,AttendanceRate,GPA,Major,PartTimeJob,ExtraCurricularActivities,Performance
0,1,Male,24,37,90.75,3.47,Arts,Yes,No,Good
1,2,Female,22,37,74.90,2.32,Education,No,No,Good
2,3,Male,22,10,53.36,2.38,Business,No,No,Good
3,4,Male,24,10,70.26,3.46,Science,Yes,No,Good
4,5,Male,18,19,74.87,2.31,Education,Yes,No,Good
5,6,Female,20,17,86.01,2.47,Business,Yes,No,Good
6,7,Male,19,21,55.33,3.93,Arts,No,No,Excellent
7,8,Male,18,14,57.00,2.51,Education,No,No,Good
8,9,Male,19,9,63.18,3.32,Business,No,No,Good
9,10,Female,24,1,63.32,3.96,Engineering,Yes,Yes,Excellent
11,12,Male,19,4,62.54,2.04,Science,No,Yes,Good
12,13,Male,20,1,81.65,2.49,Business,No,No,Good
13,14,Male,23,32,74.71,3.66,Engineering,Yes,No,Excellent
14,15,Female,19,34,78.66,3.73,Arts,Yes,Yes,Excellent
15,16,Male,24,28,91.91,3.54,Business,Yes,No,Excellent

Part 4: Data Cleaning

In [90]:
# Check for missing values in the dataset and display the number of missing values in each column
df.isnull()

,StudentID,Gender,Age,StudyHoursPerWeek,AttendanceRate,GPA,Major,PartTimeJob,ExtraCurricularActivities,Performance
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,False,False,False,False

In [91]:
df.isnull().sum()

StudentID                    0
Gender                       0
Age                          0
StudyHoursPerWeek            0
AttendanceRate               0
GPA                          0
Major                        0
PartTimeJob                  0
ExtraCurricularActivities    0
Performance                  0
dtype: int64

In [94]:
# Replace the missing values in the GPA column with the column mean
df["GPA"].fillna(df.GPA.mean())
df

,StudentID,Gender,Age,StudyHoursPerWeek,AttendanceRate,GPA,Major,PartTimeJob,ExtraCurricularActivities,Performance
0,1,Male,24,37,90.75,3.47,Arts,Yes,No,Good
1,2,Female,22,37,74.90,2.32,Education,No,No,Good
2,3,Male,22,10,53.36,2.38,Business,No,No,Good
3,4,Male,24,10,70.26,3.46,Science,Yes,No,Good
4,5,Male,18,19,74.87,2.31,Education,Yes,No,Good
...,...,...,...,...,...,...,...,...,...,...
495,496,Male,22,37,76.61,2.97,Science,No,No,Good
496,497,Male,23,11,56.29,3.20,Science,No,No,Good
497,498,Female,20,6,56.64,3.20,Science,No,Yes,Good
498,499,Male,22,18,57.18,2.05,Business,No,Yes,Good
499,500,Female,24,21,96.99,2.64,Engineering,No,No,Good

In [97]:
df.duplicated().sum()

np.int64(0)

In [ ]:
# Remove all duplicate rows from the dataset.
df.drop_duplicates()

,StudentID,Gender,Age,StudyHoursPerWeek,AttendanceRate,GPA,Major,PartTimeJob,ExtraCurricularActivities,Performance
0,1,Male,24,37,90.75,3.47,Arts,Yes,No,Good
1,2,Female,22,37,74.90,2.32,Education,No,No,Good
2,3,Male,22,10,53.36,2.38,Business,No,No,Good
3,4,Male,24,10,70.26,3.46,Science,Yes,No,Good
4,5,Male,18,19,74.87,2.31,Education,Yes,No,Good
...,...,...,...,...,...,...,...,...,...,...
495,496,Male,22,37,76.61,2.97,Science,No,No,Good
496,497,Male,23,11,56.29,3.20,Science,No,No,Good
497,498,Female,20,6,56.64,3.20,Science,No,Yes,Good
498,499,Male,22,18,57.18,2.05,Business,No,Yes,Good
499,500,Female,24,21,96.99,2.64,Engineering,No,No,Good

Part 5: Combining Data

In [117]:
# Create a new DataFrame called activities with the following data: 
# StudentID  
# Scholarship Club 
# 1 Yes Robotics 
# 2 No Sports 
# 3 Yes Music 
# 4 No Art 
# 5 Yes Coding 
 
 
# Then: 
# 1. Save it as activities.csv. 
# 2. Read the file into a new DataFrame. 
# 3. Display the first 5 rows
data = [
    {"StudentID": 1, "Scholarship": "Yes", "Club": "Robotics"},
    {"StudentID": 2, "Scholarship": "No",  "Club": "Sports"},
    {"StudentID": 3, "Scholarship": "Yes", "Club": "Music"},
    {"StudentID": 4, "Scholarship": "No",  "Club": "Art"},
    {"StudentID": 5, "Scholarship": "Yes", "Club": "Coding"}
]
activities = pd.DataFrame(data)
activities
activities.to_csv("activities.csv", index=False)
df_activities=pd.read_csv("activities.csv")
df_activities.iloc[0:5]

   StudentID Scholarship      Club
0          1         Yes  Robotics
1          2          No    Sports
2          3         Yes     Music
3          4          No       Art
4          5         Yes    Coding

In [121]:
# Merge the original student dataset with activities.csv using the StudentID column. 
# Display the merged DataFrame

merged_df=pd.merge(df,df_activities, on="StudentID")
merged_df

,StudentID,Gender,Age,StudyHoursPerWeek,AttendanceRate,GPA,Major,PartTimeJob,ExtraCurricularActivities,Performance,Scholarship,Club
0,1,Male,24,37,90.75,3.47,Arts,Yes,No,Good,Yes,Robotics
1,2,Female,22,37,74.90,2.32,Education,No,No,Good,No,Sports
2,3,Male,22,10,53.36,2.38,Business,No,No,Good,Yes,Music
3,4,Male,24,10,70.26,3.46,Science,Yes,No,Good,No,Art
4,5,Male,18,19,74.87,2.31,Education,Yes,No,Good,Yes,Coding

In [122]:
df.columns

Index(['StudentID', 'Gender', 'Age', 'StudyHoursPerWeek', 'AttendanceRate',
       'GPA', 'Major', 'PartTimeJob', 'ExtraCurricularActivities',
       'Performance'],
      dtype='object')

In [135]:
# Create another DataFrame containing 3 new students with the same columns as the 
# original dataset. 
# Then: 
# 1. Save it as new_students.csv. 
# 2. Read the file. 
# 3. Append it to the original dataset using concat(). 
# 4. Display the last 6 rows of the final DataFrame.

new_students = pd.DataFrame({
    "StudentID": [11, 12, 13],
    "Gender": ["Male", "Female", "Male"],
    "Age": [20, 22, 21],
    "StudyHoursPerWeek": [25, 30, 18],
    "AttendanceRate": [90.5, 85.0, 78.3],
    "GPA": [3.6, 3.2, 2.9],
    "Major": ["Engineering", "Science", "Business"],
    "PartTimeJob": ["No", "Yes", "No"],
    "ExtraCurricularActivities": ["Yes", "No", "Yes"],
    "Performance": ["Excellent", "Good", "Good"]
})
new_students
new_students.to_csv("new_students.csv", index=False)
pd.read_csv("new_students.csv")

final_df = pd.concat([df, new_students], ignore_index=True)
final_df.tail(6)

,StudentID,Gender,Age,StudyHoursPerWeek,AttendanceRate,GPA,Major,PartTimeJob,ExtraCurricularActivities,Performance
497,498,Female,20,6,56.64,3.20,Science,No,Yes,Good
498,499,Male,22,18,57.18,2.05,Business,No,Yes,Good
499,500,Female,24,21,96.99,2.64,Engineering,No,No,Good
500,11,Male,20,25,90.50,3.60,Engineering,No,Yes,Excellent
501,12,Female,22,30,85.00,3.20,Science,Yes,No,Good
502,13,Male,21,18,78.30,2.90,Business,No,Yes,Good

Bonus Question (Optional)

In [137]:
# Use join() to add the Scholarship column from the activities DataFrame to the 
# original dataset after setting StudentID as the index for both DataFrames. 

df_index = df.set_index("StudentID")
activities_index = df_activities.set_index("StudentID")

joined_df = df_index.join(activities_index[["Scholarship"]])

joined_df

,Gender,Age,StudyHoursPerWeek,AttendanceRate,GPA,Major,PartTimeJob,ExtraCurricularActivities,Performance,Scholarship
StudentID,,,,,,,,,,
1,Male,24,37,90.75,3.47,Arts,Yes,No,Good,Yes
2,Female,22,37,74.90,2.32,Education,No,No,Good,No
3,Male,22,10,53.36,2.38,Business,No,No,Good,Yes
4,Male,24,10,70.26,3.46,Science,Yes,No,Good,No
5,Male,18,19,74.87,2.31,Education,Yes,No,Good,Yes
...,...,...,...,...,...,...,...,...,...,...
496,Male,22,37,76.61,2.97,Science,No,No,Good,NaN
497,Male,23,11,56.29,3.20,Science,No,No,Good,NaN
498,Female,20,6,56.64,3.20,Science,No,Yes,Good,NaN
499,Male,22,18,57.18,2.05,Business,No,Yes,Good,NaN
500,Female,24,21,96.99,2.64,Engineering,No,No,Good,NaN